### PR TITLE
Initial commit of rmaps for new nirspec flats: dflat, fflat and sflat

### PR DESCRIPTION
**Pull request by stscirij**
Added 3 new rmaps for nirspec flats: dflat, fflat and sflat

### CODE REVIEW

**Comment by hbushouse** [comment]
I assume there will be imap updates in conjunction with this too? At the very least the nirspec imap obviously needs updating, but because these ref types are not used by other instruments, we'll also need to update their imaps to list these 3 new types as N/A.

**Comment by stscirij** [comment]
Yes, there's still more work to be done before crds is ready to accept these new reference file types.

  Robert J.

________________________________

**Comment by jaytmiller** [comment]
One thing to keep in mind is that unless cal code is data driven by CRDS,  we don't necessarily have to add the other types to CRDS as N/A.   Yesterday Robert and I concluded "not" for these.    The determinant is whether or not a Step is always going to ask CRDS for a reference.   If CRDS is asked,  we need to define the types as N/A where appropriate.   If we know CRDS will not be asked,  we don't have to provide answers for those cases.   

The practice of always defining a type was added for the WCS types so that those Steps do not have to know when they are or are not appropriate to run.  Adding types to imaps as N/A does not necessarily have to be a universal practice.   How do you see these new types working out?

**Comment by hbushouse** [comment]
Right now the new flat_field step that gets applied to data from all instruments lists

reference_file_types = ['FLAT', 'FFLAT', 'SFLAT', 'DFLAT']

The step uses the regular 'FLAT' for all non-NIRSpec instruments, and the new 3 for NIRSpec. So, yes, it's going to result in CRDS being queried for all of these types for all exposures. Now that I think about it, that means the NIRSpec imap would also need an entry for FLAT that say N/A. Unless someone can figure out a better way to do this. I don't know how the assign_wcs step pulls it off (i.e. only listing ref types that it actually needs for a given instrument/mode).

**Comment by jaytmiller** [comment]
I added "classes" structure so the rmap uses UseAfter automatically when updating:

+    'classes' : ('Match', 'UseAfter'),

and a corresponding additional tuple of parkeys that apply to UseAfter:

e.g.

-    'parkey' : (('META.INSTRUMENT.DETECTOR',),),
+    'parkey' : (('META.INSTRUMENT.DETECTOR',), ('META.OBSERVATION.DATE', 'META.OBSERVATION.TIME')),

**Comment by jaytmiller** [comment]
OK, wait,  I think the issue is the generic prefetch so I'm going to reverse what I said to Robert.   If a Step runs at all,  I think it will try to prefetch every type whether it's needed by the current instrument or not.   So I think we will indeed need to modify imaps for the other instruments to respond with N/A.   And unless something else changes,  this is a universal issue,  every type used in a generic multi-instrument Step needs to follow suit.   So the notion of always defining a real reference,  or defining a type as N/A,  is "less optional" than I thought;  that's a pattern the prefetch requires unless Steps steer around it somehow.

**Comment by hbushouse** [comment]
Correct. If a step module has "reference_file_types" declaration in it, the pre-fetch will try to find matches for all types listed in that statement, regardless of whether or not the remaining parts of the step ever actually do an explicit call to retrieve a particular ref file. The only way around this in the past was to leave out the "reference_file_types" declaration, in which case no prefetch is done at all and we simply find out whether a given ref file type can be found later on when the step actually does a call to "get_reference_file".

**Comment by stscirij** [comment]
Can you put the reference file types declaration in an if block depending on the exposure type?  The declaration isn't in the init, so doesn't it get executed at import time?  In that case how does the module know the model type?

On Oct 8, 2016 8:18 AM, Howard Bushouse <notifications@github.com> wrote:

Correct. If a step module has "reference_file_types" declaration in it, the pre-fetch will try to find matches for all types listed in that statement, regardless of whether or not the remaining parts of the step ever actually do an explicit call to retrieve a particular ref file. The only way around this in the past was to leave out the "reference_file_types" declaration, in which case no prefetch is done at all and we simply find out whether a given ref file type can be found later on when the step actually does a call to "get_reference_file".

**Comment by hbushouse** [comment]
The "reference_file_types" declaration occurs within the class definition of the step object, but before the definition of the process method, so it's in a part of the code that's unexecutable (at least as far as I can tell, but what do I know?) and hence it's not possible to have it occur with some set of if/else blocks that depend on instrument or mode. Besides it's way before the data model has even been loaded, so you don't even know what instrument/mode you're working with yet. The stpipe infrastructure reads the list of ref type definitions when it instantiates each step class and then does calls to CRDS to query for those ref files. It's either that layer within stpipe that loads the data model and sends it as an argument to the CRDS query, or it just sends the file name and something in CRDS loads it into a data model. At which point you finally know what instrument and mode you're dealing with.

**Comment by stscirij** [comment]
So I guess I don't see how stpipe knows what the type of model is.  Wouldn't it be clearer if we put the ref types declaration in an init for the step class, then call super on that class so the init of the base class is executed as well?
Probably more than we want to worry about right now, easier to just adjust the imaps...

On Oct 8, 2016 1:36 PM, Howard Bushouse <notifications@github.com> wrote:

The "reference_file_types" declaration occurs within the class definition of the step object, but before the definition of the process method, so it's in a part of the code that's unexecutable (at least as far as I can tell, but what do I know?) and hence it's not possible to have it occur with some set of if/else blocks that depend on instrument or mode. Besides it's way before the data model has even been loaded, so you don't even know what instrument/mode you're working with yet. The stpipe infrastructure reads the list of ref type definitions when it instantiates each step class and then does calls to CRDS to query for those ref files. It's either that layer within stpipe that loads the data model and sends it as an argument to the CRDS query, or it just sends the file name and something in CRDS loads it into a data model. At which point you finally know what instrument and mode you're dealing with.

**Comment by philhodge** [comment]
Here's an example:

x.py contains:
(jwstdev)bash-4.1$ cat x.py

class dummy(object):

     reference_file_types = ['extract1d']

     def __init__(self):
         print("dummy")

 >>> import x

 >>> print("{}".format(x.dummy.reference_file_types))
['extract1d']

So reference_file_types is accessible as soon as a module is imported.

Phil

**Pull request merged**
