### PR TITLE
Opus 2015 3dms

### PR DESCRIPTION
**Pull request by jhunkeler**
Implement changes from 2015.3

### CODE REVIEW

**Comment by jhunkeler** [comment]
@jaytmiller This looks more manageable than what was in http://www.stsci.edu/~jhunk/diffs/crds.diff

**Comment by jaytmiller** [comment]
Hi Joe,

This doesn't look like stuff which should merge to master,  it looks like stuff which should already be on master/trunk for the most part.  I checked one or two and they appeared to be present.

Todd

**Comment by jhunkeler** [comment]
Hi Todd,

I agree, we should probably just close this out. I remember seeing the 
changes get merged in manually shortly after we migrated this to GH.

Joe

**Comment by jaytmiller** [comment]
We agreed to close this.

**Pull request closed without merging**
