### PR TITLE
CCD 666 Support redefined RSCD reference files

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Resolves [CCD-666](https://jira.stsci.edu/browse/CCD-666)

WIP [CCD-650](https://jira.stsci.edu/browse/CCD-650)

Note: Inclusion here was unintentional, but this will implement everything. Only the NIRSpec version has not been tested, but we'll leave that for test. The files related here were in PR #736, which has been approved. That PR will simply be removed in favor of this one.

### CODE REVIEW

**Comment by stscieisenhamer** [comment]
And its confirmed that it is a file issue. One of the three files are actually correct and certify as so.

**Comment by stscieisenhamer** [comment]
They haven't been officially delivered anywhere, yet. I was just doing this on dev.

**Comment by jaytmiller** [comment]
I figured you were doing it on DEV,   I was just wondering if Jane is going to update her files when it's time to submit for real.   That's an indicator of whether or not unique_rowkeys is actually going to be useful or more of a drag during real world file submissions.

**Comment by jemorrison** [comment]
I am still learning how to submit the files. What is the process to  "submit for real"
Do I give them to Misty who passes them to you ? I think the unique row key is useful because it found the mistake I made.

**Comment by stscieisenhamer** [comment]
@jemorrison Yep, attach back to the issue, which you have already done. Once I push this onto TEST, "they"/Misty will deliver. Once that is checked out, things will go to OPS.

**Comment by matt-mcmaster** [comment]
You would either attach the files to the JIRA issue and Misty could deliver them from there, or put them in a directory that Misty has access to and she'd deliver them. In order for you to deliver the files via the Extended Batch Submit page, you'd need to be access to the CRDS servers. There is a step-by-step guide on how to deliver the files on the ReDCaT Team confluence page.

**Pull request merged**
