### PR TITLE
CRDS-401 add LAMP_MODE to the CUBEPAR PARKEYS

### PR DESCRIPTION
**Pull request by stscieisenhamer**
WIP [CRDS-401](https://jira.stsci.edu/browse/CRDS-401)

To fix unit tests, rmap specs for various instrument `pars-tweakregstep` have been added.

### CODE REVIEW

**Review by stscirij — COMMENTED** [review]
The cubepar part looks good, I'll leave the tweakreg parts for @eslavich to approve

**Review by eslavich — APPROVED** [review]
LGTM!

**Comment by eslavich** [comment]
It occurred to me to check and see if we have any tpn validations on rmap LAMP_MODE values.  I don't see anything in there, is that something we need?

**Comment by stscirij** [comment]
It can take one of the values in ['BRIGHTOBJ', 'FIXEDSLIT', 'GRATING-ONLY', 'IFU', 'MSASPEC', 'NONE'], if you want to check that

**Comment by stscieisenhamer** [comment]
Ideally, the datamodel checking should deal with validation of the values. Worth a check however.

**Pull request merged**
