### PR TITLE
various minor improvements to CI

### PR DESCRIPTION
**Pull request by zacharyburnett**
~runs tests in parallel with `pytest-xdist`,~ add `workflow_dispatch` to `ci.yml` for manually starting tests, and also a `concurrency` block to manage multiple pushes to the same branch

### CODE REVIEW

**Review by stscieisenhamer — COMMENTED** [review]
are the failing tests related to this change?

**Comment by zacharyburnett** [comment]
> are the failing tests related to this change?

I don't think so; the tests run, but some fail intermittently

**Comment by stscieisenhamer** [comment]
Looking again. The two errors, both for test_check_archive_file_api_*, indicate that the argument `--cov=crds` is being passed to the crds call `CheckArchiveScript` as the `prog` argument to `ArgumentParser`. This is indeed not correct, but have no clue as to how that is occurring.

**Comment by zacharyburnett** [comment]
> Looking again. The two errors, both for test_check_archive_file_api_*, indicate that the argument `--cov=crds` is being passed to the crds call `CheckArchiveScript` as the `prog` argument to `ArgumentParser`. This is indeed not correct, but have no clue as to how that is occurring.

appears to have been fixed in 4fc7f6fea4b7c50f3cf41ded14a399f8301dd2d8; I'm not sure why though

**Pull request merged**
