### PR TITLE
First stab at adding a Roman observatory package,  still much to do. Taken from Todd's work.

### PR DESCRIPTION
**Pull request by jbdoggett**
Adds roman package demoing a context featuring only WFI FLAT.
Adds fake .tpn files illustrating .tpn setup if .tpns are utilized.  (... rmap checking,  need something).
Adds preliminary WFI FLAT type spec.
Adds crds.roman.proto-cache directory containing two initial roman contexts, fake server_config, one fake ASDF reference.
Adds a faked WFI FLAT ASDF file derived from NIRCAM SPECWCS.
Spikes derivations of the crds.roman.locate and .schema modules from JWST.   Still significant code duplication.
  Lots of updates to roman locate.py and schema.py to drop FITS <-> datamodels translations.
Tweaked a few things to make them work better for the "bootstrapping" use case.
Created some roman "envs" files for configuring CRDS,  paritcularly envs/roman-proto.sh
Improved exception handling for loading type specs.   Added CrdsTypeSpecError exception.
Generalized observatory check to ALL_OBSERVATORIES in heavy_client.
Added roman to ./install for automatically generating roman's combined_specs.json and spec checksums
Added roman to setup.py
Fixed reference_name_to_ld_tpn_text refactoring error
Fixes to prototype rmap and imap.
Added envs/roman-proto.sh for prototyping roman rules in crds/roman/proto-cache.
Dropped unused exception in jwst + roman locate.py (MissingDependencyError)
Improved I/O factory handling for ASDF/Roman/JWST.
Added --roman switch to all command line programs.
Modified newcontext to always use pathless mappings when adding/replacing files
in pmaps and imaps.   This eliminates a confusing error in which files are given
the explicit relative path ./ which makes recursive loads impossible except for
loads directly from the cache mappings directory.
Eliminated "x corresponds to y  in context z" certify info message for .pmaps
   where it is non-sensical.
Added test_roman.py to root directory which assumes sourcing envs/roman-proto.sh

### CODE REVIEW

**Comment by jbdoggett** [comment]
I have no idea how to diagnosis the problem for this pull request much less fix it. @nden @eslavich

**Comment by eslavich** [comment]
> I have no idea how to diagnosis the problem for this pull request much less fix it.

The Travis failure, right?  I think it may have just been a transient connection issue.  I restarted the job and hopefully it will pass this time around.

**Comment by nden** [comment]
This is not Todd's entire branch. It's missing the last 6 commits. If you can't add them here, close this PR, update and create a new PR.

**Comment by jbdoggett** [comment]
starting over

**Pull request closed without merging**
