### PR TITLE
Add whitelightstep parameter references for miri, nircam, and nirspec

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Resolves [CCD-978](https://jira.stsci.edu/browse/CCD-978)
WIP: Add specs for [CRDS-390](https://jira.stsci.edu/browse/CRDS-390), [391](https://jira.stsci.edu/browse/CRDS-391), [392](https://jira.stsci.edu/browse/CRDS-392)

### CODE REVIEW

**Comment by stscieisenhamer** [comment]
Don't see the error when running tests locally and the error does not seem related to the PR.

**Review by eslavich — APPROVED** [review]
LGTM.  We have an issue in the queue to address that test failure: https://jira.stsci.edu/browse/CCD-981

**Review by eslavich — COMMENTED** [review]
Oops.. I just noticed, doesn't the combined_specs.json need to be updated?

**Comment by stscieisenhamer** [comment]
not sure how combined_specs was left out. going in now.

**Review by eslavich — APPROVED** [review]

**Pull request merged**
