### PR TITLE
Support new WFC3 IMPHTTAB columns

### PR DESCRIPTION
**Pull request by eslavich**
Four new columns were added to each binary table in the UVIS reference file (one of the column names varies by table).

### CODE REVIEW

**Review by stscieisenhamer — APPROVED** [review]
Ohhh, brutal.

**Review by jaytmiller — COMMENTED** [review]
I don't fully understand the changes to unique_rowkeys.  1)  I sort of expected the opposite.  2) unique_rowkeys  has a kind of built-in "optional" behavior where if a column is not present, it is just dropped from the "row id tuple".

**Comment by eslavich** [comment]
> I don't fully understand the changes to unique_rowkeys. 1) I sort of expected the opposite. 2) unique_rowkeys has a kind of built-in "optional" behavior where if a column is not present, it is just dropped from the "row id tuple".

I changed that because OBSMODE alone is the unique key to those rows -- they don't want multiple rows to share the same OBSMODE, even if other column values are different.  Does that rhyme with the change I made, or did I misunderstand something?

**Comment by jaytmiller** [comment]
Nope,  that sounds exactly right,   just make sure they really are unique.

**Pull request merged**
